# Generated by Django 4.2 on 2023-04-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers_app', '0002_onlineretailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodels',
            name='retailer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='readers_app.onlineretailer'),
            preserve_default=False,
        ),
    ]
