# Generated by Django 4.2 on 2023-05-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers_app', '0005_bookmodels_avg_rating_bookmodels_number_of_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodels',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='readers_app.onlineretailer'),
        ),
    ]
